export const Msg = {
  OK: "OK",
  CANCEL: "CANCELLED",
  ERROR: "ERROR",
  WRONG_PATH: "WRONG PATH",
  NO_TOKEN: "NO_TOKEN",
  INCORRECT_LOGIN_INFO: "INCORRECT_LOGIN_INFO",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PASSWORD_IS_WRONG: "PASSWORD_IS_WRONG",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
};
export const Errors = {
  CANCEL: "CANCELLED",
  ERROR: "ERROR",
  WRONG_PATH: "WRONG PATH",
  NO_TOKEN: "NO_TOKEN_PROVIDED",
  MISSING_FIELDS: "MISSING_FIELDS",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  404: "404 NOT FOUND",
  500: "SERVER ERROR",
  400: "BAD REQUEST",
};
